### ISSUE TITLE
[ENH] make sure OSF link in example walkthrough works

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#102]
Somehow `https://osf.io/w2nu3/` did not work in `babs-init --input` on CUBIC on 5/31/2023, using conda env `mydatalad`. Printed messages as below. Need to check this again to it was just temporarly not working, and to make sure this link really works robustly, as it's used in the example walkthrough!

```
Registering the input dataset(s)...
Cloning input dataset #1: 'BIDS'
install(error): inputs/data/BIDS (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:       
- osf://w2nu3
  CommandError: 'git -c diff.ignoreSubmodules=none clone --progress osf://w2nu3 /cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis/inputs/data/BIDS' failed with exitcode 128 [err: 'Cloning into '/cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis/inputs/data/BIDS'...
fatal: HTTPSConnectionPool(host='api.osf.io', port=443): Max retries exceeded with url: /v2//guids/w2nu3/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8aa94bbb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))']]

`babs-init` failed! Below is the error message:
Traceback (most recent call last):
  File "/gpfs/fs001/cbica/projects/BABS/babs/babs/cli.py", line 234, in babs_init_main
    babs_proj.babs_bootstrap(input_ds,
  File "/gpfs/fs001/cbica/projects/BABS/babs/babs/babs.py", line 373, in babs_bootstrap
    dlapi.clone(dataset=self.analysis_path,
  File "/cbica/projects/BABS/miniconda3/envs/mydatalad/lib/python3.9/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
  File "/cbica/projects/BABS/miniconda3/envs/mydatalad/lib/python3.9/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
  File "/cbica/projects/BABS/miniconda3/envs/mydatalad/lib/python3.9/site-packages/datalad/interface/base.py", line 940, in _execute_command_
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'install',
  'message': ('Failed to clone from any candidate source URL. Encountered '
              'errors per each url were:\n'
              '- %s',
              'osf://w2nu3\n'
              "  CommandError: 'git -c diff.ignoreSubmodules=none clone "
              '--progress osf://w2nu3 '
              "/cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis/inputs/data/BIDS' "
              "failed with exitcode 128 [err: 'Cloning into "
              "'/cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis/inputs/data/BIDS'...\n"
              "fatal: HTTPSConnectionPool(host='api.osf.io', port=443): Max "
              'retries exceeded with url: /v2//guids/w2nu3/ (Caused by '
              "NewConnectionError('<urllib3.connection.HTTPSConnection object "
              'at 0x7f8aa94bbb50>: Failed to establish a new connection: '
              "[Errno -3] Temporary failure in name resolution'))']"),
  'path': '/cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis/inputs/data/BIDS',
  'refds': '/cbica/projects/BABS/data/test_babs_multi-ses_toybidsapp/analysis',
  'source': {'default_destpath': 'w2nu3',
             'giturl': 'osf://w2nu3',
             'source': 'osf://w2nu3',
             'type': 'giturl',
             'version': None},
  'source_url': 'https://osf.io/w2nu3/',
  'status': 'error',
  'type': 'dataset'}]
```

**Comment by zhao-cy** [comment]
Tried again on cubic today using the same conda env, but this time I directly used `datalad clone`, and it turns out to be fine:

```
(mydatalad) babs@cubic-sattertt1:data$ datalad clone https://osf.io/w2nu3/
[INFO   ] Remote origin uses a protocol not supported by git-annex; setting annex-ignore                                                   
install(ok): /cbica/projects/BABS/data/w2nu3 (dataset)
```

Dependent packages versions:
```
datalad 0.18.3
git version 2.34.1
git-annex version: 10.20230215-gd24914f2a
datalad_container 1.1.9
datalad_osf 0.2.3.1
```

TODO:
To make sure using this link in BABS example walkthrough is alright, by running `babs-init` on cubic with this OSF link.

**Comment by zhao-cy** [comment]
Confirmed today that this OSF link is still working, by successfully running `babs-init` (BABS version: 0.0.3) on cubic with this OSF link.

Used `babs_demo` conda env. Dependent packages versions:
```
datalad 0.18.3
git version 2.34.1
git-annex version: 10.20230215-gd24914f2a
datalad_container 1.1.9
datalad_osf 0.2.3.1
```

Also, Dorota has followed example walkthrough on MIT cluster, and it turned out fine too. So probably it was a temporary error? Okay to proceed to close this issue?

**Comment by zhao-cy** [comment]
Temporary thing - might related to cubic or OSF. No worries for now.
