### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 0: ordinal not in range(256)

### ISSUE THREAD

**Issue by Michael-Sun** [PennLINC/babs#139]
This issue can be fixed by prepending the babs-check-setup command with: 
export LC_ALL=en_US.UTF-8
set PYTHONIOENCODING=utf-8

(/dartfs-hpc/rc/home/j/f003z4j/miniconda3/envs/physio/babs) [f003z4j@n09 my_BABS_project]$ babs-check-setup \
>     --project-root ${PWD} \
>     --job-test
Will check setups of BABS project located at: /dartfs-hpc/rc/home/j/f003z4j/babs_demo2/my_BABS_project
Will submit a test job for testing; will take longer time.
Below is the configuration information saved during `babs-init` in file 'analysis/code/babs_proj_config.yaml':

type_session: multi-ses
type_system: slurm
input_ds:
  $INPUT_DATASET_#1:
    name: BIDS
    path_in: https://osf.io/w2nu3/
    path_data_rel: inputs/data/BIDS
    is_zipped: false
container:
  name: toybidsapp-0-0-7
  path_in: /dartfs-hpc/rc/home/j/f003z4j/babs_demo2/toybidsapp-container

Checking the BABS project itself...
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/j/f003z4j/miniconda3/envs/physio/babs/bin/babs-check-setup", line 8, in <module>
    sys.exit(babs_check_setup_main())
  File "/dartfs-hpc/rc/home/j/f003z4j/miniconda3/envs/physio/babs/lib/python3.9/site-packages/babs/cli.py", line 296, in babs_check_setup_main
    babs_proj.babs_check_setup(input_ds, args.job_test)
  File "/dartfs-hpc/rc/home/j/f003z4j/miniconda3/envs/physio/babs/lib/python3.9/site-packages/babs/babs.py", line 666, in babs_check_setup
    print(CHECK_MARK + " All good!")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 0: ordinal not in range(256)

**Comment by zhao-cy** [comment]
Thank you Michael for reporting this issue + suggested way to get around it! I'll add to the docs (example walkthrough + `babs-check-setup`)
