### ISSUE TITLE
[FIX] docs build failed: No module named 'babs'

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#16]
from `conf.py`:

```
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pennlinc-babs/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pennlinc-babs/checkouts/latest/docs/source/conf.py", line 27, in <module>
    import babs
ModuleNotFoundError: No module named 'babs'
```

See my readthedocs account for more

**Comment by zhao-cy** [comment]
see https://stackoverflow.com/questions/13372068/importerror-no-module-named-for-my-code-on-readthedocs

Remember also to change configurations in readthedocs!!
